apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
  labels:
    cluster: scout-karpenter-test
spec:
  template:
    metadata:
      labels:
        intent: general
        nodepool: default
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: kubernetes.amazonaws.com/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: kubernetes.amazonaws.com/instance-generation
          operator: Gt
          values: ["4"]
        - key: kubernetes.amazonaws.com/instance-cpu
          operator: In
          values: ["4", "8", "16"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - m5.xlarge
            - m5.2xlarge
            - m5.4xlarge
            - c5.2xlarge
            - r5.xlarge
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["us-east-1a", "us-east-1b", "us-east-1c"]
      expireAfter: 720h
  limits:
    cpu: "1000"
    memory: 1000Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
